# Write CD: send the dockerized service to your gcp
name: Service 1 (CD)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches:
    - main
    - develop
    - prod

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GKE_CRED }}
        export_default_credentials: true
    - name: Install kubectl
      run: |
        sudo gcloud components install kubectl
        gcloud --quiet components update
    - name: Authenticate to GKE and Deploy
      env:
        GKE_CRED: ${{ secrets.GKE_CRED }}
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GKE_SA: ${{ secrets.GKE_SA }}
        GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
        GCP_ZONE: ${{ secrets.GCP_ZONE }}
        run: |
          ./service1/scripts/gcloud.sh
          kubectl apply -f ./service1/scripts/k8s.yaml
