# Write CI: build, lint (fmt and clippy), test with tarpaulin
name: Service 1 (CI)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Lint with Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
